repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest before commit
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        require_serial: true
        stages: [pre-commit]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [src/]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: []
